name: Release Build

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          chmod a+x ./install-dependents.sh
          chmod a+x ./build.sh
          ./install-dependents.sh
          ./build.sh

      - name: Add binaries to production files
        run: wget --input-file=lib-urls.txt --directory-prefix=production-code/daemon/lib/

      - name: Stage linux and windows builds
        run: |
          cp -r production-code dist_linux
          mv production-code dist_windows
          mv dist_linux mcemanager_linux
          mv dist_windows mcemanager_windows

      - name: Copy startup scripts
        run: |
          cp prod-scripts/linux/* mcemanager_linux/
          cp prod-scripts/windows/* mcemanager_windows/

      - name: Copy license
        run: |
          cp LICENSE mcemanager_linux/LICENSE
          cp LICENSE mcemanager_windows/LICENSE

      - name: Copy node runtime to windows build
        run: |
          wget https://nodejs.org/download/release/latest-v20.x/win-x64/node.exe -O mcemanager_windows/daemon/node_app.exe
          cp mcemanager_windows/daemon/node_app.exe mcemanager_windows/web/node_app.exe

      - name: Create archive
        run: |
          mv mcemanager_linux/ mcemanager/
          tar czf mce_manager_linux_release.tar.gz mcemanager/
          tar --exclude='mcemanager/daemon' --exclude='mcemanager/start-daemon.sh' -czf mce_manager_linux_web_only_release.tar.gz mcemanager/
          tar --exclude='mcemanager/web' --exclude='mcemanager/start-web.sh' -czf mce_manager_linux_daemon_only_release.tar.gz mcemanager/
          rm -rf mcemanager/
          mv mcemanager_windows/ mcemanager/
          zip -r mce_manager_windows_release.zip mcemanager/
          zip -r mce_manager_windows_web_only_release.zip mcemanager/ -x "mcemanager/daemon/*"
          zip -r mce_manager_windows_daemon_only_release.zip mcemanager/ -x "mcemanager/web/*"

      - name: Upload assets to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mce_manager_windows_release.zip
            mce_manager_windows_web_only_release.zip
            mce_manager_windows_daemon_only_release.zip
            mce_manager_linux_release.tar.gz
            mce_manager_linux_web_only_release.tar.gz
            mce_manager_linux_daemon_only_release.tar.gz
